### ISSUE TITLE
Mod not working with lethalexpansion 

### ISSUE THREAD

**Issue by Eggosss** [xCursedbreathx/CustomMoonPrices#11]
This mod stops working with modded moons when using the lethalexpansion but works when using the lethalexpansioncore. Don't know which end this is on so figured i would check and see here first to see if it is meant to be like that or not. 

https://github.com/xCursedbreathx/CustomMoonPrices/assets/163368757/dcaf3b1d-1735-411c-a97f-34d7e00f3ea9

https://github.com/xCursedbreathx/CustomMoonPrices/assets/163368757/1737b21f-dea7-4d66-8d2f-aebf37f0cc32

**Comment by xCursedbreathx** [comment]
I'll have a look at it tomorrow, I haven't actually changed anything, but maybe I'll find an error that's being spit out.

**Comment by xCursedbreathx** [comment]
I have now looked to see if I can find an error somewhere as to why this does not work, but unfortunately I cannot find a reason why this does not work.

But since the moons are registered normally with LethalExpansion it should be somewhere in my mod I just don't know exactly where.

So it might take a while until I find the error.

**Comment by Eggosss** [comment]
All good i have found a workaround for right now. I just  restart the game switching between them whenever needed.

**Comment by xCursedbreathx** [comment]
Unfortunately, I cannot find the issue.

Since Lethal Expansion is currently no longer being developed, I will set the report here to won't fix status and when Lethal Company version v50 is out and the error persists I will look again, but currently I can't find a solution.
