### ISSUE TITLE
On v50 mod breaks ESC and TAB bindings 

### ISSUE THREAD

**Issue by kStoko23** [xCursedbreathx/CustomMoonPrices#13]
After v50 of lethal company rolled out, both ESC and TAB key stopped working, no matter the use case (terminal, pause menu). After removing only this mod, issue seems to be fixed so it probably is the cause. Also we encountered issue that our money got wiped clean in the middle of a run, not sure if its caused by this mod or not.

**Comment by xCursedbreathx** [comment]
Have uploaded a Update to Thunderstore waiting for approval now.

This Update Fixes the Terminal and ESC/TAB Key.

Since the mod does not process the player's money, the problem with the money should come from somewhere else.

But I'm not sure if this continues to happen, you can contact me again and I'll check again, I'll leave the issue open for now.
